const {JSDOM,VirtualConsole}=require('jsdom');
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),cp=require('child_process'),path=require('path'),os=require('os');
// Developer-only test dependency: jsdom. Not required for running the application.
const root=path.resolve(__dirname,'..');
if(!fs.existsSync(path.join(root,'bescheide-2024','manifest.json'))){console.log('DOM fixture test skipped: optional notice fixture not shipped. Runtime and annual tests remain available.');process.exit(0);}
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'cay-dom-'));
const server=cp.spawn('python',['app.py','--port','0','--data-dir',path.join(temp,'data'),'--no-browser'],{cwd:root});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,label,timeout=7000){let end=Date.now()+timeout;while(Date.now()<end){if(await fn())return;await sleep(30)}throw new Error('Timeout: '+label)}
let output='';server.stdout.on('data',x=>output+=x);server.stderr.on('data',x=>output+=x);
(async()=>{
 await until(()=>output.includes('http://127.0.0.1:'),'server');
 const url=output.match(/http:\/\/127.0.0.1:\d+/)[0];
 const html=await (await fetch(url)).text();
 const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 const dom=new JSDOM(html,{url,runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});const w=dom.window,ctx=dom.getInternalVMContext();
 w.fetch=(input,options)=>fetch(new URL(input,url),options);w.confirm=()=>true;w.structuredClone=structuredClone;
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
 for(const name of ['app.js','features.js','banking.js','intake.js','pdf-review.js','workspace.js','annual.js','euer.js'])vm.runInContext(fs.readFileSync(path.join(root,'dist',name),'utf8'),ctx,{filename:name});
 const run=expr=>vm.runInContext(expr,ctx),q=s=>w.document.querySelector(s);
 await until(()=>q('h1'),'initial render');
 assert(q('.home-calm'),'simplified homepage');
 assert.equal(w.document.querySelectorAll('.home-action').length,3,'three main actions');
 assert.equal(w.document.querySelectorAll('.welcome-glass').length,0,'no duplicated welcome');
 assert.equal(q('.nav-more').open,false,'secondary navigation collapsed');
 assert.equal(w.document.querySelectorAll('.home-details[open]').length,0,'details collapsed initially');
 for(const view of ['inbox','overview','documents','transactions','tasks','calendar','settings','chat','knowledge','safety','banking','assessments','taxyear']){
   run(`navigate('${view}')`);await sleep(100);
   assert(q('h1'),view+' heading');assert(!/\bundefined\b|\bNaN\b/.test(q('#main').innerHTML),view+' invalid values');
 }
 const themeBefore=run('document.documentElement.dataset.theme');await run("action('toggle-theme',{dataset:{}})");assert.notEqual(run('document.documentElement.dataset.theme'),themeBefore,'theme toggled');assert(q('#theme-toggle').getAttribute('aria-label'));await run("action('toggle-theme',{dataset:{}})");assert.equal(run('document.documentElement.dataset.theme'),themeBefore,'theme toggled back');
 run('documentForm()');
 q('#f-title').value='Testentwurf mit Datei';
 q('#f-document_date').value='2025-04-03';
 w.testFile=new w.File(['Originalbeleg 49,90 Euro.'], 'beleg.txt',{type:'text/plain'});
 run('app.pendingFile=testFile');
 await run("queueDraft(document.querySelector('#document-form'))");
 assert(q('.save-state').textContent.includes('Entwurf gespeichert'));
 run('app.suppressDraft=true;closeModal();app.suppressDraft=false');
 await run('refresh()');
 assert.equal(run('app.data.drafts.length'),1);
 await run("resumeDraft('document-form:new')");
 assert(q('#file-label').textContent.includes('gespeichertem Entwurf'));
 await run("submit(document.querySelector('#document-form'))");
 assert.equal(run('app.data.documents.length'),1);assert.equal(run('app.data.drafts.length'),0);
 run('closeModal();transactionForm()');
 assert(q('[name="payment_method"]'),'cash payment method');
 q('[name="payment_method"]').value='cash';q('[name="payment_method"]').dispatchEvent(new w.Event('change',{bubbles:true}));
 assert(!q('.cash-source-wrap').classList.contains('cash-details-hidden'),'cash source visible');
 q('[name="expense_kind"]').value='business_meal';q('[name="expense_kind"]').dispatchEvent(new w.Event('change',{bubbles:true}));
 assert(!q('.meal-details-wrap').classList.contains('cash-details-hidden'),'meal fields visible');
 await run("queueDraft(document.querySelector('#transaction-form'))");
 run('app.suppressDraft=true;closeModal();app.suppressDraft=false');
 await run("resumeDraft('transaction-form:new')");
 assert(!q('.cash-source-wrap').classList.contains('cash-details-hidden'),'restored cash fields visible');
 assert(!q('.meal-details-wrap').classList.contains('cash-details-hidden'),'restored meal fields visible');
 assert(q('.bank-account-wrap').classList.contains('cash-details-hidden'),'restored cash hides bank account');
 q('[name="payment_method"]').value='unknown';q('[name="payment_method"]').dispatchEvent(new w.Event('change',{bubbles:true}));
 for(const [name,value] of Object.entries({amount:'49,90',paid_on:'2025-04-03',partner:'Testanbieter',title:'Software',account_id:'account_volksbank'}))q(`[name="${name}"]`).value=value;
 w.receiptFile=new w.File(['Originalrechnung 49,90 Euro.'], 'rechnung-april.txt',{type:'text/plain'});run('app.transactionReceiptFile=receiptFile');
 await run("submit(document.querySelector('#transaction-form'))");
 assert.equal(run('app.data.transactions.length'),1);
 assert.equal(run('app.data.transactions[0].amount_cents'),4990);
 assert.equal(run('app.data.transactions[0].document_ids.length'),1);assert.equal(run('app.data.documents.length'),2);
 await run("action('seed-tasks',{dataset:{}})");assert.equal(run('app.data.tasks.length'),8);
 run('navigate("banking");bankImportForm("account_n26")');
 w.csvFile=new w.File(['Date,Payee,Account number,Transaction type,Payment reference,Amount (EUR)\n2025-04-04,Google,,Transfer,Revenue,12.34\n'], 'n26.csv',{type:'text/csv'});
 run('app.bankFile=csvFile');
 await run("submit(document.querySelector('#bank-import-form'))");
 assert(q('#bank-commit-form'),'preview form');assert.equal(q('.import-choice').value,'create');
 q('[name="checked"]').checked=true;
 await run("submit(document.querySelector('#bank-commit-form'))");
 assert.equal(run('app.data.transactions.length'),2);
 assert.equal(run('app.data.transactions.find(t=>t.partner==="Google").amount_cents'),1234);
 await run("action('bank-pdf',{dataset:{}})");assert(q('#bank-import-form'),'PDF uses the statement intake form');run('closeModal()');
 run('navigate("chat")');await sleep(100);assert(q('#chat-form'));
 q('[name="question"]').value='Welche Belege fehlen?';
 await run("queueDraft(document.querySelector('#chat-form'))");
 assert(q('.save-state').textContent.includes('Entwurf gespeichert'));
 await run('refresh()');assert(run('app.data.drafts.some(d=>d.key.startsWith("chat-form"))'));
 run('navigate("assessments")');assert(q('[data-action="import-assessments"]'),'notice import available');
 await run("action('import-assessments',document.querySelector('[data-action=import-assessments]'))");
 assert.equal(run('app.data.assessments.cases.length'),1);
 assert.equal(run('app.data.transactions.length'),2,'notice import creates no payments');
 assert.equal(run('app.data.assessments.cases[0].documents.length'),6);
 assert(!q('[data-action="import-assessments"]'),'completed import no longer offered');
 assert(q('.nav-more').open,'notice navigation visible');
 run('app.year=2024;navigate("settings")');
 assert(q('#profile-form [name="year"]').value==='2024');
 await run("action('profile-proposal',document.querySelector('[data-action=profile-proposal]'))");
 assert.equal(q('[name="vat_status"]').value,'regular');
 assert.equal(q('[name="taxation"]').value,'unknown');
 assert.equal(q('[name="filing_status"]').value,'submitted');
 q('[name="personal_notes"]').value='Student im Jahr 2025; BAföG prüfen.';
 await run("submit(document.querySelector('#profile-form'))");
 assert.equal(run('app.data.tax_profiles.find(p=>p.year===2024).vat_status'),'regular');
 run('app.year=2025;render()');
 assert.equal(q('[name="vat_status"]').value,'unknown','VAT never inherited across years');
 assert.equal(q('[name="personal_notes"]').value,'Student im Jahr 2025; BAföG prüfen.');
 q('[name="filing_status"]').value='open';
 await run("queueDraft(document.querySelector('#profile-form'))");
 run('app.year=2026;render()');
 await run("resumeDraft('profile-form:new:2025')");
 assert.equal(run('app.year'),2025,'profile draft restores correct year');
 assert.equal(q('[name="filing_status"]').value,'open');
 await run("submit(document.querySelector('#profile-form'))");
 assert.equal(run('app.data.settings.filing_2025'),'open');
 assert(!run('app.data.drafts.some(d=>d.key.startsWith("profile-form"))'));
 run(`app.legal={catalog:[{id:'estg',title:'Einkommensteuergesetz',url:'https://www.gesetze-im-internet.de/estg/xml.zip',web_url:'https://www.gesetze-im-internet.de/estg/'}],versions:[{source_id:'estg',id:'v1',source_type:'xmlzip',units:2,retrieved_at:'2026-09-29',reviewed:0}],checks:[{source_id:'estg',error:'Einkommensteuergesetz: HTTP 503. Vorhandene Fassungen bleiben erhalten.'}],status:{running:false}};navigate('knowledge')`);
 assert(q('#legal-status').textContent.includes('1 von 1 Originalquellen gespeichert'));
 assert(q('.legal-errors').textContent.includes('Einkommensteuergesetz'));
 assert(q('[data-action="retry-failed-legal"]'));
 assert(q('.source-card a').href.endsWith('/estg/'),'opens readable law page, not ZIP');
 assert(q('.source-card .tag').textContent==='Gespeichert');
 assert.equal(q('.source-card details').open,false,'expert dating collapsed');
 assert(!q('#main').textContent.includes('Datierung offen'));
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({ok:true,views:13,document_draft_with_file:true,cent_transaction:true,bank_import_preview_and_commit:true,chat_draft:true,notice_import:true,year_profile_and_draft:true,source_retry_ui:true,errors}));
 dom.window.close();
})().then(()=>server.kill('SIGINT')).catch(e=>{console.error(e);server.kill('SIGINT');process.exitCode=1});
server.on('exit',()=>fs.rmSync(temp,{recursive:true,force:true}));
