const fs=require('fs'),path=require('path'),cp=require('child_process'),assert=require('assert/strict');
const {chromium}=require('playwright');
const base=path.join(__dirname,'..','test-output','euer');fs.mkdirSync(base,{recursive:true});const data=path.join(base,'run-'+Date.now(),'data');
let server,output='',browser,page,url;const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function start(){output='';server=cp.spawn(process.env.CAY_TEST_PYTHON||(process.platform==='win32'?'python':'python3'),[path.join(__dirname,'euer_server.py'),'--port','0','--data-dir',data,'--no-browser']);server.stdout.on('data',d=>output+=d);server.stderr.on('data',d=>output+=d);for(let n=0;n<160&&!output.includes('http://127.0.0.1:');n++)await sleep(100);url=output.match(/http:\/\/127.0.0.1:\d+/)?.[0];assert(url,output);}
async function stop(){if(!server||server.exitCode!==null)return;const p=new Promise(r=>server.once('exit',r));server.kill('SIGINT');await p;}
async function field(name,value){await page.locator('#modal [name="'+name+'"]').fill(value)}
async function save(){await page.locator('#modal [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#modal').open);await page.waitForFunction(()=>app.euer?.year===2025);}
async function open(){await page.goto(url);await page.locator('h1').waitFor();await page.locator('[data-view=euer]').first().click();await page.waitForFunction(()=>app.euer?.rows.length===106);}
(async()=>{
 await start();browser=await chromium.launch({executablePath:process.env.CAY_TEST_CHROME||undefined,args:['--disable-gpu','--disable-software-rasterizer','--no-sandbox'],headless:true});
 page=await browser.newPage({locale:'de-DE',viewport:{width:1480,height:1050}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await open();assert.match(await page.locator('.version').innerText(),/0.4.0/);assert.equal(await page.evaluate(()=>app.euer.counts.open),33);assert.equal(await page.evaluate(()=>app.euer.counts.excluded),73);
 const ids=await page.evaluate(()=>Object.fromEntries(app.euer.rows.filter(r=>r.partner.includes('· Test')).map(r=>[r.partner.split(' ·')[0],r.id])));
 await page.locator(`[data-action=euer-allocation][data-id="${ids['Studio Tools']}"]`).click();await page.locator('#modal [name=position]').selectOption('50');await field('vat','120,00');await field('note','Rechnung und betriebliche Nutzung geprüft.');await page.locator('#modal [name=confirmed]').check();await page.locator('#modal [type=submit]').click();await page.waitForFunction(()=>document.querySelector('#modal .form-error')?.textContent.includes('nicht übersteigen'));
 await field('vat','19,00');await save();await page.waitForFunction(()=>app.euer.counts.confirmed===1);assert.equal(await page.evaluate(()=>app.euer.expense_cents),11900);
 await page.locator(`[data-action=euer-allocation][data-id="${ids.Videoplattform}"]`).click();await page.locator('#modal [name=position]').selectOption('15');await field('vat','38,00');await field('note','Auszahlung gemäß Abrechnung 2025 geprüft.');await page.locator('#modal [name=confirmed]').check();await save();await page.waitForFunction(()=>app.euer.income_cents===23800);
 await page.locator(`[data-action=euer-allocation][data-id="${ids.Kameratechnik}"]`).click();await page.locator('#modal [name=position]').selectOption('asset');await field('vat','190,00');await field('note','Anschaffung für Betrieb. Netto nicht sofort abziehen.');await page.locator('#modal [name=confirmed]').check();await save();await page.waitForFunction(()=>app.euer.counts.confirmed===3);assert.equal(await page.evaluate(()=>app.euer.expense_cents),30900);
 await page.locator('[data-action=euer-tab][data-tab=entries]').click();await page.locator('[data-kind=asset]').click();await field('title','Kamera · Testanlage');await page.locator('#modal [name=position]').selectOption('33');await field('acquired_on','2025-02-03');await field('opening','0,00');await field('additions','1000,00');await field('depreciation','200,00');await field('disposals','0,00');await page.locator('#modal [name=tx_id]').selectOption(ids.Kameratechnik);await field('note','Jahres-AfA 2025 aus synthetischem Anlagenachweis, linear.');await page.locator('#modal [name=confirmed]').check();await save();await page.waitForFunction(()=>app.euer.entries.length===1);
 await page.locator('[data-kind=supplement]').click();await field('title','Tagespauschale · Test');await page.locator('#modal [name=position]').selectOption('66');await field('amount','60,00');await field('note','10 geprüfte Tage. Keine zeitgleiche Arbeitszimmerpauschale.');await page.locator('#modal [name=confirmed]').check();await save();await page.waitForFunction(()=>app.euer.entries.length===2);assert.equal(await page.evaluate(()=>app.euer.expense_cents),56900);
 await page.locator('[data-action=euer-tab][data-tab=check]').click();await page.locator('#euer-check-form [name=records]').check();await page.locator('#euer-check-form [type=submit]').click();await page.waitForFunction(()=>app.euer.checks.records===true);
 await page.locator('[data-action=euer-tab][data-tab=payments]').click();const draftId=await page.evaluate(()=>app.euer.rows.find(r=>r.status==='open').id);await page.locator(`[data-action=euer-allocation][data-id="${draftId}"]`).click();await field('note','ENTWURF BLEIBT ERHALTEN');await page.waitForTimeout(750);await page.locator('#modal [data-action=close-modal]').first().click();await page.waitForFunction(()=>app.data.drafts.some(d=>d.key.startsWith('euer-allocation-form')));const draftKey=await page.evaluate(id=>app.data.drafts.find(d=>d.key.includes(id)).key,draftId);await page.evaluate(key=>resumeDraft(key),draftKey);assert.equal(await page.locator('#modal [name=note]').inputValue(),'ENTWURF BLEIBT ERHALTEN');assert.equal(await page.locator('#modal [name=confirmed]').isChecked(),false);await page.locator('#modal [data-action=close-modal]').first().click();await page.waitForTimeout(250);
 await page.locator('[data-action=euer-tab][data-tab=report]').click();await page.screenshot({path:path.join(base,'report-light.png'),fullPage:true});await page.evaluate(async()=>{applyTheme('dark');await new Promise(r=>setTimeout(r,300))});await page.screenshot({path:path.join(base,'report-dark.png'),fullPage:true});await page.evaluate(async()=>{applyTheme('light');await new Promise(r=>setTimeout(r,300))});
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(base,'report-mobile.png'),fullPage:true});await page.setViewportSize({width:1480,height:1050});
 const down=page.waitForEvent('download');await page.locator('[data-action=euer-export]').click();const dl=await down;await dl.saveAs(path.join(base,'report.csv'));const csv=fs.readFileSync(path.join(base,'report.csv'),'utf8');assert(csv.includes('238,00'));assert(csv.includes('569,00'));assert(csv.includes('Nicht bestätigte Positionen'));await page.pdf({path:path.join(base,'report-print.pdf'),format:'A4',printBackground:true,margin:{top:'14mm',right:'12mm',bottom:'14mm',left:'12mm'}});
 await page.locator('[data-action=euer-tab][data-tab=ai]').click();await page.locator('#euer-ai-form [name=question]').fill('Lies die Rechnungstexte für meine EÜR 2025. Prüfe jede betriebliche Zahlung und lass ungeklärte Steuerbeträge offen. ENDE MEINES AUFTRAGS.');await page.locator('#euer-ai-form [type=submit]').click();await page.waitForFunction(()=>app.euerRuns?.[0]?.state==='error',null,{timeout:40000});let run=await page.evaluate(()=>app.euerRuns[0]);assert.equal(run.done,36);assert.equal(run.total,105);assert.equal(run.question.endsWith('ENDE MEINES AUFTRAGS.'),true);const completed=run.id;
 await stop();await start();await open();await page.locator('[data-action=euer-tab][data-tab=ai]').click();await page.locator('[data-action=euer-resume]').click();await page.waitForFunction(()=>app.euerRuns?.[0]?.state==='complete',null,{timeout:60000});run=await page.evaluate(()=>app.euerRuns[0]);assert.equal(run.id,completed);assert.equal(run.done,105);assert.equal(run.suggestions.length,33);assert(run.coverage.every(d=>d.worker===d.parts&&d.reviewer===d.parts));assert.equal(await page.evaluate(()=>app.euer.counts.confirmed),3);
 const calls=fs.readFileSync(path.join(data,'qa-calls.jsonl'),'utf8').trim().split('\n').map(JSON.parse);assert.equal(calls.filter(c=>c.model=== 'qwen3.8:27b'&&['document','transaction'].includes(c.kind)).length,36);
 await page.screenshot({path:path.join(base,'ai-complete.png')});await page.locator(`[data-action=euer-proposal][data-id="${ids['Studio Tools']}"][data-role=coordinator]`).first().click();assert.equal(await page.locator('#modal [name=vat]').inputValue(),'19,00');assert.equal(await page.locator('#modal [name=confirmed]').isChecked(),false);await page.locator('#modal [data-action=close-modal]').first().click();
 await page.locator('[data-view=chat]').first().click();await page.locator('#chat-form [name=question]').fill('Kannst du mir meine EÜR erklären?');await page.locator('#chat-form [type=submit]').click();await page.waitForFunction(()=>app.chatItems?.some(c=>c.question==='Kannst du mir meine EÜR erklären?'&&c.state==='complete'));assert.equal(await page.evaluate(()=>app.chatItems.find(c=>c.question==='Kannst du mir meine EÜR erklären?').annual),null);
 await page.locator('[data-view=euer]').first().click();await page.waitForFunction(()=>app.euer?.year===2025);await page.locator('[data-action=euer-tab][data-tab=payments]').click();await page.locator('[data-action=euer-filter][data-filter=confirmed]').click();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(base,'payments-light.png')});await page.evaluate(async()=>{applyTheme('dark');await new Promise(r=>setTimeout(r,300))});await page.screenshot({path:path.join(base,'payments-dark.png')});await page.evaluate(async()=>{applyTheme('light');await new Promise(r=>setTimeout(r,300))});
 await page.locator('#year-select').selectOption('2026');await page.waitForFunction(()=>app.euer?.year===2026);assert.match(await page.locator('#main').innerText(),/Formularzuordnung ist für 2025/);assert.equal(await page.locator('[data-action=euer-allocation]').count(),0);await page.locator('#year-select').selectOption('2025');await page.waitForFunction(()=>app.euer?.year===2025);
 await stop();await start();await open();assert.equal(await page.evaluate(()=>app.euer.expense_cents),56900);assert.equal(await page.evaluate(()=>app.data.transactions.length),106);
 assert.deepEqual(errors,[]);const result={ok:true,synthetic_records:106,business_rows:33,private_rows:73,financial_ui_save:true,invalid_vat_blocked:true,asset_and_supplement_saved:true,csv_and_print_export:true,year_check_saved:true,form_draft_restored:true,independent_readers:true,all_text_parts_read:true,interrupted_run_resumed:true,completed_worker_not_rerun:true,proposal_not_auto_accepted:true,free_euer_question_not_rerouted:true,restart_preserved_data:true,future_year_blocked:true,dark_light_mobile:true,errors};fs.writeFileSync(path.join(base,'browser-result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
})().catch(async e=>{console.error(e);if(page){await page.screenshot({path:path.join(base,'failure.png')}).catch(()=>{});console.error((await page.locator('#main').innerText().catch(()=>'' )).slice(-2200));console.error((await page.locator('#modal').innerText().catch(()=>'' )).slice(-1600));}process.exitCode=1}).finally(async()=>{if(browser)await browser.close();await stop();fs.writeFileSync(path.join(base,'server-log.txt'),output)});
